package kr.co.ecommtech.epsi.ui.services;

public enum Event {
    EL_EVENT_LOGIN,
    EL_EVENT_LOGOUT,
    EL_EVENT_GET_ACCESSTOKEN,
    EL_EVENT_GET_TOKEN,
    EL_EVENT_READ_NFC_PIPEINFO,
    EL_EVENT_WRITE_NFC_DONE,
    EL_EVENT_WRITE_NFC_FAIL,
    EL_EVENT_WRITE_NFC_SET_PW_FAIL,
    EL_EVENT_WRITE_NFC_DEL_PW_OK,
    EL_EVENT_WRITE_NFC_DEL_PW_FAIL,
    EL_EVENT_UPLOADED_PHOTO,
    EL_EVENT_UPLOADED_PHOTO_FAIL,
    EL_EVENT_DB_SAVE_SUCCESS,
    EL_EVENT_DB_SAVE_FAIL,
    EL_EVENT_REFRESH,
    EL_EVENT_MAP_REFRESH,
}

